spring:
    datasource:
        url: jdbc:h2:file:E:/copyDaily/Project/Pblicis/theatreBooking
        username: sa
        password: 
        driverClassName: org.h2.Driver
    h2:
        console:
            path: /h2-console-onlinetheatre
            enabled: true
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        
            
      